spring.application.name=techstore-api

spring.datasource.url=jdbc:postgresql://postgres:5432/techstore
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
server.port=8083

jwt.secret=mi-clave-secreta-muy-larga-para-jwt-que-debe-tener-al-menos-256-bits
jwt.expiration=3600000
