spring.application.name=techstore-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/techstore}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8083

jwt.secret=mi-clave-secreta-muy-larga-para-jwt-que-debe-tener-al-menos-256-bits
jwt.expiration=3600000

aws.region=us-east-1
aws.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/062999438355/techstore-audit-queue