spring.application.name=techstore-api

server.port=${SERVER_PORT:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5433/techstore?sslmode=disable}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:mi-clave-secreta-muy-larga-para-jwt-que-debe-tener-al-menos-256-bits}
jwt.expiration=${JWT_EXPIRATION:3600000}

aws.region=${AWS_REGION:us-east-1}
aws.sqs.queue-url=${AWS_SQS_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/062999438355/techstore-audit-queue}